FROM mcr.microsoft.com/devcontainers/base:jammy

RUN apt update \
    && apt install -y \
    gcc \
    libc6-dev \
    libgl1-mesa-dev \
    libgl1-mesa-dev \
    libxcursor-dev \
    libxi-dev \
    libxinerama-dev \
    libxrandr-dev \
    libxxf86vm-dev \
    libasound2-dev \
    pkg-config
